#pragma once

// moba/fx/angle.hpp -- binary angle measure, and the trig that reads from it.
//
// REPRESENTATION. u16, 65536 raw units to a full turn ("BAM16").
//   - wraparound is free and exact: unsigned overflow IS modulo one turn, so
//     no branch, no fmod, no accumulated drift
//   - the useful angles are exact -- a quarter turn is 16384, not 1.5707963
//   - the raw value indexes the sine table directly
//   Degrees and radians can do none of that: 360 does not divide a binary
//   range, and radians are not rational.
//
// NO FLOATING POINT ANYWHERE, including at compile time. std::sin is not
// constexpr, and where a compiler allows it anyway the answer is the host
// libm's and differs per platform -- which is a desync baked into a constant.
// The table is generated by integer CORDIC at consteval time instead.
//
// CORDIC, in one paragraph. Rotating (x,y) by theta needs sin and cos, which
// is what we are trying to compute. But factoring out cos leaves a rotation
// whose SHAPE depends only on tan(theta), with cos as a uniform scale. So
// pick only angles where tan(theta) = 2^-i, and the multiply becomes a shift.
// Those angles -- 45, 26.565, 14.036 ... -- can reach any target by adding and
// subtracting, because each is smaller than the sum of all the ones after it;
// it is a binary search on the angle. The dropped cos factors multiply out to
// a constant K, the same for every input, because the same n steps always run
// and only their SIGNS vary. Start at (K, 0) and you finish at (cos, sin).
// Run the identical loop driving y to zero instead of the angle, and you get
// atan2 -- and the vector's length as a by-product.
//
// ACCURACY, measured rather than argued. Swept over all 65536 representable
// angles -- which is the ENTIRE input domain of sin and cos, so these are
// proofs rather than samples. clang and gcc agree bit for bit.
//
//   sin, cos vs libm          worst 1.229e-05  ==  0.81 fx LSB
//   sin^2 + cos^2 - 1         worst 3.04e-05
//   sin(-a) == -sin(a)        EXACT, zero violations
//   atan2(sin a, cos a) == a  worst 1 BAM unit
//   atan2 vs libm             worst 1 BAM unit, over magnitudes 1 .. 2^30
//
// The four cardinals are exact by construction, not by luck -- see the pin at
// the foot of make_sin_table().
//
// TODO: [phase 1] Quantise aim input to this type at capture, day one.
//       Un-quantised aim is the classic rollback desync and is expensive to
//       retrofit once replays exist.

#include <array>
#include <bit>
#include <moba/core/assert.hpp>
#include <moba/core/types.hpp>
#include <moba/fx/fx.hpp>

namespace moba {
struct [[nodiscard]] angle {
  /// raw units per full turn. The scale factor, not a value: comparing an
  /// angle against SCALE is a category error, and a full turn IS zero.
  static constexpr i32 SCALE = 65536;

  u16 raw = 0;

  // so that angle is not an aggregate and `angle a{ 4 }` does not compile
  constexpr angle() noexcept = default;

  static constexpr angle from_raw(u16 r) noexcept {
    angle a{};
    a.raw = r;
    return a;
  }

  /// exact rational turns, resolved at compile time: from_turns(1, 4) is a
  /// quarter turn. consteval because it throws -- a throw only becomes a
  /// compile error when the call is actually evaluated at compile time.
  [[nodiscard]] static consteval angle from_turns(i32 num, i32 den) {
    if (den == 0) throw "angle::from_turns: zero denominator";
    const i64 wide = detail::fdiv<i64>(static_cast<i64>(num) * SCALE, den);
    return from_raw(static_cast<u16>(wide));
  }

  //  from_degrees floors too, and is exact only for multiples of 45°
  //  since 65536/360 isn't an integer
  [[nodiscard]] static constexpr angle from_degrees(i32 d) noexcept {
    const i64 wide = detail::fdiv<i64>(static_cast<i64>(d) * SCALE, 360);
    return from_raw(static_cast<u16>(wide));
  }

  // wrapping behavior for angle is required
  constexpr angle  operator+(angle o) const noexcept;
  constexpr angle  operator-(angle o) const noexcept;
  constexpr angle  operator-() const noexcept;
  constexpr angle &operator+=(angle o) noexcept;
  constexpr angle &operator-=(angle o) noexcept;

  // equality works for angles
  constexpr bool operator==(const angle &) const = default;

  // <=> (relational operators) are poorly defined for angles, so we delete
  constexpr auto operator<=>(angle) const = delete;

  static const angle ZERO, QUARTER, HALF, THREE_QUARTER;
};

// The cast goes OUTSIDE the arithmetic. static_cast<u16>(SCALE) is 0, because
// 65536 does not fit a u16 -- the cast would silence the diagnostic and leave
// HALF equal to ZERO.
inline constexpr angle angle::ZERO = angle::from_raw(0);
inline constexpr angle angle::QUARTER
    = angle::from_raw(static_cast<u16>(SCALE / 4));
inline constexpr angle angle::HALF
    = angle::from_raw(static_cast<u16>(SCALE / 2));
inline constexpr angle angle::THREE_QUARTER
    = angle::from_raw(static_cast<u16>(SCALE * 3 / 4));

// wrap by construction, never clamp. u16 arithmetic promotes to int, so the
// narrowing cast back to u16 is what performs the modulo -- well defined since
// C++20 mandates two's complement, which types.hpp already pins.
constexpr angle angle::operator+(angle o) const noexcept {
  return from_raw(static_cast<u16>(raw + o.raw));
}
constexpr angle angle::operator-(angle o) const noexcept {
  return from_raw(static_cast<u16>(raw - o.raw));
}
constexpr angle angle::operator-() const noexcept {
  return from_raw(static_cast<u16>(-static_cast<i32>(raw)));
}
constexpr angle &angle::operator+=(angle o) noexcept {
  *this = *this + o;
  return *this;
}
constexpr angle &angle::operator-=(angle o) noexcept {
  *this = *this - o;
  return *this;
}

/// signed shortest path from `from` to `to`: facing 350 degrees with a target
/// of 10 gives +20, not -340. What a turn rate consumes.
///
/// EXACTLY OPPOSITE ANGLES HAVE NO SHORTEST DIRECTION. A half turn is 32768,
/// which does not fit i16, so it lands on -32768: opposite angles always turn
/// the same way. deterministic, and the reason this is written down is that
/// two call sites disagreeing about it would be a desync.
[[nodiscard]] constexpr i16 shortest_delta(angle from, angle to) noexcept {
  return static_cast<i16>(to.raw - from.raw);
}

[[nodiscard]] constexpr fx    sin(angle a) noexcept;
[[nodiscard]] constexpr fx    cos(angle a) noexcept;
[[nodiscard]] constexpr angle atan2(fx y, fx x) noexcept;

namespace detail {

/* CORDIC */

/// iterations. the angle error after n steps is about 2^-n, and sin has to
/// land inside half an fx LSB (2^-17), so 18 is the floor and 20 leaves
/// margin. At 20 the iteration is no longer the dominant error term -- the
/// single narrowing in sin() is -- which is the right place to stop.
inline constexpr int CORDIC_N = 20;

/// working precision, Q2.30 in i32. values stay under 2 in magnitude, so this
/// leaves 14 guard bits above the 16 fx needs -- enough to absorb the ~4 bits
/// lost to rounding in the shifts.
inline constexpr int CORDIC_SHIFT = 30;
inline constexpr i32 CORDIC_ONE   = 1 << CORDIC_SHIFT;

/// atan(2^-i) in BAM32 -- 2^32 units per turn, so entry 0 is exactly 2^29
/// because atan(1) is 45 degrees is one eighth of a turn. BAM32 rather than
/// BAM16 because one BAM16 unit of angle moves sin by about six fx LSBs; the
/// residual angle has to be carried finer than the output.
///
// python3 -c "
// import math
// for i in range(20):
//   print(f'{round(math.atan(2**-i)/(2*math.pi)*2**32):>12}, // atan(2^-{i})')"
inline constexpr i32 ATAN_TABLE[CORDIC_N] = {
  536870912,  // atan(2^-0)
  316933406,  // atan(2^-1)
  167458907,  // atan(2^-2)
  85004756,   // atan(2^-3)
  42667331,   // atan(2^-4)
  21354465,   // atan(2^-5)
  10679838,   // atan(2^-6)
  5340245,    // atan(2^-7)
  2670163,    // atan(2^-8)
  1335087,    // atan(2^-9)
  667544,     // atan(2^-10)
  333772,     // atan(2^-11)
  166886,     // atan(2^-12)
  83443,      // atan(2^-13)
  41722,      // atan(2^-14)
  20861,      // atan(2^-15)
  10430,      // atan(2^-16)
  5215,       // atan(2^-17)
  2608,       // atan(2^-18)
  1304,       // atan(2^-19)
};

// atan(1) is exact. The sum is CORDIC's convergence limit, ~99.88 degrees --
// the largest angle the sequence can reach. Both catch a mistyped digit,
// which is otherwise invisible in transcribed data.
static_assert(ATAN_TABLE[0] == 536870912);
static_assert([] {
  i64 s = 0;
  for (i32 v : ATAN_TABLE) s += v;
  return s;
}() == 1191648895);

/// The product of every cos(atan(2^-i)) the iteration drops, in Q2.30. It
/// depends on CORDIC_N: change the iteration count and this changes with it.
///
// python3 -c "
// import math
// K = 1.0
// for i in range(20): K /= math.sqrt(1 + 2**(-2*i))
// print(round(K * 2**30))"
inline constexpr i32 CORDIC_K = 652032874;

struct cordic_xy {
  i32 x, y;
};

/// one iteration, shared by both modes. `d` is the only thing that differs
/// between them, and it is the caller's business.
///
/// the two spellings of this arithmetic must not drift, or sin() and atan2()
/// will disagree -- the same reason detail::unscale_fx exists in fx.hpp.
/// hence one step, two callers, rather than two loops.
///
/// The temporaries are load-bearing: computing x first and then using the NEW
/// x for y is the classic CORDIC bug, and it produces plausible wrong answers
/// rather than obvious ones.
///
/// @param x,y  the vector being rotated. Q2.30, updated in place.
/// @param z    the angle accumulator, BAM32, updated in place. Rotation mode
///             starts it at the target and drains it to zero; vectoring mode
///             starts it at zero and fills it with the answer.
/// @param i    iteration number, which IS the shift amount: this step rotates
///             by atan(2^-i), and multiplying by 2^-i is `>> i`.
/// @param d    +1 or -1, which way to turn this step. The ONLY thing that
///             differs between the two modes.
constexpr void cordic_step(i32 &x, i32 &y, i32 &z, int i, i32 d) noexcept {
  // nx, ny: the rotated vector, held aside because the update is SIMULTANEOUS.
  // arithmetic shift, so it floors on negatives as everything else here does.
  const i32 nx = x - (d * (y >> i));
  const i32 ny = y + (d * (x >> i));
  x            = nx;
  y            = ny;

  // pay for the rotation just performed: rotation mode drives this toward
  // zero, vectoring mode accumulates it as the result
  z -= d * ATAN_TABLE[i];
}

/// rotation mode: drive the residual angle to zero. z is BAM32 and must
/// already be folded into CORDIC's convergence range (+/- 99.88 degrees);
/// callers fold with the exact half- and quarter-turn symmetries first.
///
/// returns (cos, sin) in Q2.30. Starting at (K, 0) is what makes the final
/// magnitude exactly 1 -- the iteration grows the vector by 1/K regardless of
/// which way each step turned.
/// @param z  the angle to rotate to, BAM32. Consumed as the running debt.
/// @return   (cos, sin) in Q2.30.
[[nodiscard]] constexpr cordic_xy cordic_rotate(i32 z) noexcept {
  // the pre-paid scale: the loop multiplies length by 1/K whatever the input,
  // so starting here is what lands the result on the unit circle
  i32 x = CORDIC_K;
  i32 y = 0;
  // z < 0 means the last step overshot, so turn back. binary search
  for (int i = 0; i < CORDIC_N; ++i) cordic_step(x, y, z, i, z >= 0 ? 1 : -1);
  return { .x = x, .y = y };
}

/// vectoring mode: the same loop, driving y to zero instead. What z
/// accumulates is the angle (x, y) started at, in BAM32. Converges only in
/// the right half-plane, so callers reflect x < 0 first.
///
/// x ends as |v| / K, so the magnitude is available here too. Unused for now:
/// vec2::length goes through isqrt, which does not need the angle.
/// @param x,y  the vector to measure. Any common scale will do -- only the
///             RATIO matters, which is why atan2 may normalise it freely.
/// @return     the angle (x, y) started at, BAM32.
[[nodiscard]] constexpr i32 cordic_vector(i32 x, i32 y) noexcept {
  i32 z = 0;  // accumulates the answer as y collapses

  // turn whichever way pushes y toward zero. when y reaches it the
  // vector lies on the x-axis, and z holds every rotation it took
  // to get there
  for (int i = 0; i < CORDIC_N; ++i) cordic_step(x, y, z, i, y >= 0 ? -1 : 1);
  return z;
}

/* THE SINE TABLE */

/// 1024 entries over a full turn, linearly interpolated. linear interpolation
/// error is bounded by h^2 * max|sin''| / 8, and with h = 2pi/1024 that is
/// 4.7e-6 -- about a third of an fx LSB, so the table is matched to Q16.16
/// and 2048 entries would buy nothing measurable. 4 KB.
inline constexpr int SIN_BITS = 10;
inline constexpr int SIN_N    = 1 << SIN_BITS;  // 1024
inline constexpr int SIN_FRAC = 16 - SIN_BITS;  // 6 bits of interpolation

consteval std::array<i32, SIN_N> make_sin_table() {
  std::array<i32, SIN_N> t{};
  for (int k = 0; k < SIN_N; ++k) {
    u32  r   = static_cast<u32>(k) << SIN_FRAC;  // this entry's BAM16 angle
    bool neg = false;                            // did folding flip the sign?

    // fold into [0, 90] degrees, which is inside CORDIC's 99.88 limit. Both
    // identities are exact in BAM -- no rounding enters here.
    if (r >= 32768) {  // sin(x + 180) == -sin(x)
      r -= 32768;
      neg = true;
    }
    if (r > 16384) {  // sin(180 - x) ==  sin(x)
      r = 32768 - r;
    }

    // stored at CORDIC's Q2.30, NOT narrowed to fx here. fx is an i32 too, so
    // keeping 14 extra fractional bits is free in memory and removes one of
    // the two roundings that sin() would otherwise pay -- measured: 1.21 LSB
    // of worst-case error with two roundings, 0.81 with one.
    const cordic_xy v        = cordic_rotate(static_cast<i32>(r) << 16);
    t[static_cast<usize>(k)] = neg ? -v.y : v.y;
  }

  // The cardinals must be EXACT. Gameplay leans on a character facing east
  // having velocity exactly (speed, 0); one LSB of error there compounds every
  // tick. They land on table indices, so pinning them costs nothing.
  t[0]                                 = 0;
  t[static_cast<usize>(SIN_N / 4)]     = CORDIC_ONE;
  t[static_cast<usize>(SIN_N / 2)]     = 0;
  t[static_cast<usize>(SIN_N) * 3 / 4] = -CORDIC_ONE;
  return t;
}

/// sin over a full turn, in Q2.30. Indexed by the top 10 bits of a raw angle.
inline constexpr std::array<i32, SIN_N> SIN_TABLE = make_sin_table();

}  // namespace detail

/// table lookup plus a linear interpolation. No CORDIC at runtime, no
/// division: the interpolation divisor is 64, so it is a shift, which floors
/// and therefore matches the rounding policy for free.
[[nodiscard]] constexpr fx sin(angle a) noexcept {
  const u32 r = a.raw;                  // the BAM16 angle
  const u32 i = r >> detail::SIN_FRAC;  // table index: the top 10 bits
  // f: the low 6 bits -- how far between t0 and t1 this angle sits, out of 64.
  // Powers of two throughout, so splitting the angle is a shift and a mask.
  const i32 f = static_cast<i32>(r & ((1U << detail::SIN_FRAC) - 1));

  const i32 t0 = detail::SIN_TABLE[i];  // entry at or below this angle
  // the entry above, wrapping 1023 -> 0 because a full turn is a full circle
  const i32 t1 = detail::SIN_TABLE[(i + 1) & (detail::SIN_N - 1)];

  // Interpolate in Q2.30. |t1 - t0| peaks near a zero crossing at about
  // 6.6e6 and f is at most 63, so the product stays well inside i32.
  const i32 q = t0 + (((t1 - t0) * f) >> detail::SIN_FRAC);  // Q2.30 result

  // The single narrowing, rounded to nearest rather than floored. This is a
  // deliberate exception to the library's floor policy: floor is there so two
  // spellings of the same ARITHMETIC agree, and an approximation of a
  // transcendental is not that. Flooring here would cost a full extra LSB.
  constexpr int NB = detail::CORDIC_SHIFT - fx::SHIFT;
  return fx::from_raw((q + (1 << (NB - 1))) >> NB);
}

/// One table serves both: the quarter-turn offset wraps for free in u16.
[[nodiscard]] constexpr fx cos(angle a) noexcept {
  return sin(a + angle::QUARTER);
}

/// the only function here that runs cordic at runtime, and the only one that
/// touches no table but ATAN_TABLE.
///
/// atan2(0, 0) has no answer. asserts in debug, returns ZERO in release --
/// the same degenerate policy as shapes.hpp.
[[nodiscard]] constexpr angle atan2(fx y, fx x) noexcept {
  // NOT `x.raw != 0 && y.raw != 0` -- that rejects every axis-aligned aim.
  // Only the origin is degenerate: either component alone may be zero.
  MOBA_ASSERT(x.raw != 0 || y.raw != 0);
  if (x.raw == 0 && y.raw == 0) return angle::ZERO;

  // The axes are exactly representable and aim lands on them constantly --
  // clicking straight right has to give ZERO, not ZERO minus one unit. CORDIC
  // cannot produce them: every step rotates by a non-zero amount, so it
  // approaches an axis without ever sitting on it. Pin the four cases where an
  // exact answer exists, and the round trip through sin/cos becomes exact too.
  if (y.raw == 0) return x.raw > 0 ? angle::ZERO : angle::HALF;
  if (x.raw == 0) return y.raw > 0 ? angle::QUARTER : angle::THREE_QUARTER;

  // NORMALISE. scaling both components by the same power of two leaves the
  // angle untouched, so put the larger of the two into [2^27, 2^28):
  //   - shifting up matters because the >> i inside the loop would otherwise
  //     flush small inputs to zero and return garbage
  //   - shifting down matters because the vector grows by 1/K ~= 1.65 over the
  //     iterations, and an fx raw can already be near i32's limit
  //
  // wx, wy: the inputs widened to i64. Not for range -- so that negating
  // I32_MIN, which an fx raw can legitimately be, never happens.
  const i64 wx = x.raw;
  const i64 wy = y.raw;

  // m: the larger magnitude. It decides the shift; both components then
  // move together, which is what leaves the angle untouched. m >= 1, because
  // the both-zero case returned above.
  const i64 ax = wx < 0 ? -wx : wx;
  const i64 ay = wy < 0 ? -wy : wy;
  const i64 m  = ax > ay ? ax : ay;

  // TARGET_BIT: where m's highest set bit should land. 27 leaves room for the
  // vector growing by 1/K (~1.65) and the sqrt(2) a diagonal costs, while
  // still spending 27 bits of precision on a 16-bit answer.
  constexpr int TARGET_BIT = 27;

  // sh: how far to shift, positive to shrink. countl_zero counts leading
  // zeros, so 63 minus it is the index of the highest set bit.
  const int sh = (63 - std::countl_zero(static_cast<u64>(m))) - TARGET_BIT;

  // cx, cy: the normalised vector CORDIC consumes.
  i32 cx = static_cast<i32>(sh >= 0 ? (wx >> sh) : (wx << -sh));
  i32 cy = static_cast<i32>(sh >= 0 ? (wy >> sh) : (wy << -sh));

  // vectoring converges only for x >= 0. A half-turn reflection is exact, so
  // fold and add it back afterwards. safe to negate: normalisation has already
  // bounded both components by 2^28.
  bool flip = false;  // remember that the answer owes a half turn
  if (cx < 0) {
    cx   = -cx;
    cy   = -cy;
    flip = true;
  }

  const i32 z = detail::cordic_vector(cx, cy);

  // BAM32 -> BAM16. Through u32 so a negative angle wraps rather than
  // sign-extends: -45 degrees becomes 315, which is the same angle.
  angle a = angle::from_raw(static_cast<u16>(static_cast<u32>(z) >> 16));
  if (flip) a += angle::HALF;
  return a;
}
}  // namespace moba
